### ISSUE TITLE
Problem with download

### ISSUE THREAD

**Issue by KarolJosef** [allanvb/nova-exports#1]
Hello, I have a problem, when I perform the export, instead of downloading the exported file, it is downloading from the page where the action is being triggered. The file is being exported correctly to the storage folder, only the download is incorrect.

**Comment by KarolJosef** [comment]
I managed to solve it, I was talking about creating a symbolic link at public/storage which points to the storage/app/public directory, I just run the php artisan storage:link command and the problem was solved.

**Comment by allanvb** [comment]
> The file is being exported correctly to the storage folder, only the download is incorrect.

This happened because `rap2hpoutre/fast-excel` wich is used behind the scenes, uses the storage path to save generated files, but on download it is access from under the `public` path, so you need to take care of having symlink of `storage`.
