### ISSUE TITLE
I need help with the queryBuilder

### ISSUE THREAD

**Issue by ltd300** [allanvb/nova-exports#2]
How should I use the queryBuilder(callable $query)

I want to export only the users that belong to a company.
like
User::where('company_id', Auth::user()->company_id)->get();

How can I implement this with your "queryBuilder(callable $query) - Manipulate query builder before data exportation."

Thanks in advance!

**Comment by allanvb** [comment]
> I want to export only the users that belong to a company.

You can do this way

```php
(new ExportResourceAction($this))->queryBuilder(fn($builder) => $builder->where('company_id', auth()->user()->company_id))
```

**Comment by ltd300** [comment]
Hey, Thank you for your quick response.
it seems like is working but I'm getting this message
" An error occurred while exporting data. Trying to add value that exceeds the maximum of characters allowed in a cell (32,767)

here is the code I'm using:
 (new ExportResourceAction($this))
                ->only(['name'])
                ->queryBuilder(
                    fn($builder) => $builder->where('company_id', auth()->user()->company_id)
                ),

**Comment by allanvb** [comment]
@ltd300 you are selecting only the name but using where with company_id :)

UPD: BTW, the error message you got says that you try to fullfill the cell of an tablesheet with a larger number of chars that is allowed by the tablesheet itselft, so I guess the solution for you will be to split this column into multiple

**Comment by ltd300** [comment]
Hi Allan, 

I add it "usesDateRange()" and it works with fewer data. but still not respecting the only() or excep() methods.
The queryBuilder works as expected. 

Thank you so much for your help!
